name: Build & Deploy to RunPod Serverless

on:
  push:
    branches: [ jaehyeon ]  # 특정 브랜치에 푸시될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker Image Tag
      id: set_tag
      run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image with tag and latest
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/moneymong-pdf-parser:$TAG .
        docker tag ${{ secrets.DOCKER_USERNAME }}/moneymong-pdf-parser:$TAG ${{ secrets.DOCKER_USERNAME }}/moneymong-pdf-parser:latest

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/moneymong-pdf-parser:$TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/moneymong-pdf-parser:latest

    - name: Update RunPod Serverless with new tag
      run: |
        curl -X POST https://api.runpod.ai/v2/${{ secrets.RUNPOD_ENDPOINT_ID }}/update \
        -H "Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"image": "docker.io/${{ secrets.DOCKER_USERNAME }}/moneymong-pdf-parser:'"$TAG"'"}'
